const numbers = ['one', 'two', 'three', 'four', 'five', 'six'];
numbers.shift();
console.log(numbers);
numbers.unshift('Vilas');
console.log(numbers);
numbers.pop();
console.log(numbers);
numbers.push('Patil');
console.log(numbers);
// numbers.slice(2, 1 : 'Something');
// console.log(numbers);